#include <fstream>
#include "TeaplAst.h"
#include "TeaplaAst.h"
#include "PrintTeaplaAst.h"
#include "y.tab.hpp"

// set YACCDEBUG 1 to turn on yydebug
#define YACCDEBUG 0

using namespace std;

// Function generated by YYAC/BISON.
extern int yyparse();
// Global variable generated by YYAC/BISON
extern YYSTYPE yylval;
// Debug variable control if open debug function of YYAC/BISON. 
extern int yydebug;

// record the line and column of file which is undertaking processing.
int line, col;

A_program root;
aA_program aroot;

int main(int argc, char * argv[]) {

    #if YACCDEBUG
        yydebug = 1;
    #endif

    // line and column count from 1.
    line = 1;
    col = 1;
    
    // The argv[1] oriented file will be reopened and replace standard input stream.
    freopen(argv[1], "r", stdin);  
    // AST stream is defined as output file stream.
    ofstream ASTStream;
    // AST stream open the argv[2] oriented file.
    ASTStream.open(argv[2]);

    // Call YYAC parser.
    yyparse();

    aroot = aA_Program(root);
    print_aA_Program(aroot, ASTStream);

    // Close output file stream.
    ASTStream.close();
    return 0;
}